---
title: "HIV-1 protease inhibitor docking"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prep the structure from PDB via bio3d

```{r}
library(bio3d)

hiv1.file <- get.pdb("1hsg")
hiv1.file
```

Read in the HIV1 protease file. Then read the file

```{r}
hiv <- read.pdb(hiv1.file)
hiv
```

Trim the pdb file to just show proteins

```{r}
prot <- trim.pdb(hiv, "protein")
prot
```

Do the same for ligands

```{r}
lig <- trim.pdb(hiv, "ligand")
lig
```

Write the previous two files 

```{r}
write.pdb(prot, file="1hsg_protein.pdb")  

write.pdb(lig, "1hsg_ligand.pdb")
```

Read the ADT files or something like that

```{r}
library(bio3d) 
res <- read.pdb("all.pdbqt", multi=TRUE)
res
```

Write the all.pdbqt file into a pdb format so that VMD can read it
```{r}
write.pdb(res, "results.pdb")
```

RMSD to crystal structure experiment.  The output is the distance in Angstroms
```{r}
res <- read.pdb("all.pdbqt", multi=TRUE) 
ori <- read.pdb("1hsg_ligand.pdbqt")
rmsd(ori, res)
```

